### PR TITLE
feat: modifiable main/eye icon through exports

### PR DESCRIPTION
**Pull request by mahanmoulaei**
Preview: https://youtu.be/Sat_JFo1sQ0

Note: once 3rd eye is active and there are multiple main icons set through exports, it uses the top/highest customizable icon from the target options index that is not hidden(based on `canInteract` property and etc)

Example usage for global and entity exports:
```lua
ox_target:addGlobalVehicle({
    mainIcon = 'fa-brands fa-internet-explorer',
    mainIconColor = '#eb0546',
    {
        name = ...,
        icon = ...,
        label = ...,
        bones = ...,
        canInteract = ...,
        onSelect = ...
    }
})
```

Example usage for zone exports:
```lua
ox_target:addBoxZone({
    mainIcon = 'fa-brands fa-internet-explorer',
    mainIconColor = '#eb0546',
    coords = ...
    size = ...,
    rotation = ...,
    debug = ...,
    drawSprite = ...,
    options = ...
})
```

### CODE REVIEW

**Comment by thelindat** [comment]
A bunch of options deciding (and fighting over) the eye-icon leaves a sour taste in my mouth.

**Comment by mahanmoulaei** [comment]
I could do it so each export type can have its own icon and icon color, but I thought people might want to change their icon based on the available options:
something like green icon for alive players and red icon for dead players which should be configured through exports based on `canInteract` property of each export, not a global icon for player type export?

p.s I just noticed the preview video was expired so I uploaded a new one in case you haven't been able to see the previous one

**Comment by thelindat** [comment]
Can't say I'm a fan of turning the eye into a rainbow, and none of what was shown looked pleasing in any way. An export to set the current icon/colour would be _okay_, if people want to puke out Skittles they can at least put in the effort.

Need to be able to reset the icon back to the _current_ one as well (it's not font awesome, because their eye is super chonky).

**Comment by mahanmoulaei** [comment]
What is your desired Google Materials class CSS?
I got it working but in my opinion, the eye-icon from Google Materials looks really small(I might have missed something)

```css
.material-symbols-outlined {
  font-variation-settings:
    'FILL' 1,
    'wght' 400,
    'GRAD' 200,
    'opsz' 48
}
```

**Pull request closed without merging**
